In [3]:
import numpy as np # We'll be storing our data as numpy arrays
import os # For handling directories
from PIL import Image # For handling the images
import matplotlib.pyplot as plt
import matplotlib.image as mpimg # Plotting

In [4]:
lookup_gesture = dict()
reverselookup_gesture = dict()
lookup_seq = dict()
reverselookup_seq = dict()
seqLens=[]
count = 0
count_seq = 0
for i in range(0, 2):
    
    for j in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'):
        if not j.startswith('.'): # If running this code locally, this is to ensure you aren't reading in hidden folders
                for k in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+
                                           '/sequences/' + j + '/' + 'train' + '/'):
                    imgseq = 0
                    for l in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+
                                    '/sequences/' + j + '/' + 'train' + '/' + k + '/'):
                            lookup_seq[j] = count_seq
                            reverselookup_seq[count_seq] = j
                            count_seq = count_seq +1
                            imgseq= imgseq +1
                    seqLens.append(imgseq)
                            
                    
count_seq
Seqlength=max(seqLens)

In [7]:
x_train = []
X_train =[]
y_train = []
final_img_count_train = 0
seq_img_count  = 0
ges_img_count = 0
sub_img_count = 0
img_count = 0
for i in range(0, 2): # select 2 subject areas only
    ges_img_count = 0
    for j in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'):
        if not j.startswith('.'): # Again avoid hidden folders
             seq_img_count = 0 # To tally images of a given gesture
        for k in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'
                                  + j + '/' + 'train' + '/'):
               
                if not k.startswith('.'): # Again avoid hidden folders
                    img_count = 0
                    x_train.clear()
                    for l in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'
                                          + j + '/' + 'train' + '/' + k + '/'):
                        img = Image.open('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'
                                          + j + '/' + 'train' + '/' + k + '/' + l).convert('L')
                        # Read in and convert to greyscale
                        img = img.resize((320, 120))
                        arr = np.array(img)
                        x_train.append(arr) 
                        img_count = img_count + 1
                        #y_values = np.full((img_count, 1), lookup_seq[j]) 
                        #y_values = lookup_seq[j]
                           
                    if img_count < max(seqLens):
                        for m in range (img_count , Seqlength):
                            x_train.append(np.ones((120,320)))
                            m = m + 1
                            
                    y_values = str(j)
                    y_train.append(y_values)
                    X_train.append(x_train)
                    seq_img_count = seq_img_count + m
                        
                
        ges_img_count = ges_img_count + seq_img_count
            #print("ges_img_count",ges_img_count)
    sub_img_count = sub_img_count + ges_img_count
    #print("sub_img_count",sub_img_count)
final_img_count_train = final_img_count_train + sub_img_count        
print(final_img_count_train)
X_train = np.array(X_train, dtype = 'float32')
y_train = np.array(y_train)
#y_train = y_train.reshape(final_img_count_train, 1) # Reshape to be the correct size
#y_train = y_train.reshape(1, -1)

27963


In [8]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
y_train1 = encoder.fit_transform(y_train)
print(y_train1)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [9]:
print(X_train.shape)
print(y_train1.shape)
X_train[0:1,]

(717, 39, 120, 320)
(717, 11)


array([[[[4., 3., 3., ..., 1., 3., 4.],
         [4., 3., 5., ..., 4., 5., 4.],
         [5., 5., 4., ..., 3., 5., 3.],
         ...,
         [4., 5., 2., ..., 4., 6., 4.],
         [7., 4., 8., ..., 4., 4., 3.],
         [3., 2., 5., ..., 4., 3., 6.]],

        [[3., 4., 4., ..., 3., 3., 4.],
         [5., 4., 5., ..., 4., 3., 3.],
         [5., 3., 1., ..., 4., 3., 2.],
         ...,
         [0., 5., 4., ..., 5., 4., 6.],
         [5., 5., 6., ..., 5., 4., 5.],
         [4., 4., 4., ..., 4., 6., 4.]],

        [[4., 4., 4., ..., 4., 3., 3.],
         [5., 3., 3., ..., 2., 3., 3.],
         [5., 3., 4., ..., 5., 4., 4.],
         ...,
         [6., 4., 4., ..., 4., 3., 4.],
         [4., 4., 4., ..., 5., 5., 4.],
         [4., 3., 4., ..., 4., 4., 3.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [10]:
x_test = []
X_test=[]
y_test = []
final_img_count_test = 0
seq_img_count  = 0
ges_img_count = 0
sub_img_count = 0
img_count = 0
for i in range(0, 2): # select 2 subject areas only
    ges_img_count = 0
    for j in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'):
        if not j.startswith('.'): # Again avoid hidden folders
            seq_img_count = 0 # To tally images of a given gesture
            for k in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'
                                + j + '/' + 'test' + '/'):
                if not k.startswith('.'): # Again avoid hidden folders
                    x_test.clear()
                    img_count = 0
                    for l in os.listdir('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'
                                        + j + '/' + 'test' + '/' + k + '/'):
                        img = Image.open('C:/MITB/Term 4/AML/Project/leaphandgestuav/MultiModHandGestUAV/0'+str(i)+'/sequences/'
                                          + j + '/' + 'test' + '/' + k + '/' + l).convert('L')
                        # Read in and convert to greyscale
                        img = img.resize((320, 120))
                        arr = np.array(img)
                        x_test.append(arr) 
                        img_count = img_count + 1
                        #y_values = np.full((img_count, 1), lookup_seq[j]) 
                        #y_values = lookup_seq[j]
                    
                    #X_test.append(x_test)
                    if img_count < max(seqLens):
                         for m in range (img_count , Seqlength):
                                x_test.append(np.ones((120,320)))
                                m = m + 1
                            
                    y_values = str(j)
                    y_test.append(y_values)
                    X_test.append(x_test) 
                    seq_img_count = seq_img_count + m
                    
                     
            ges_img_count = ges_img_count + seq_img_count
            #print("ges_img_count",ges_img_count)
    sub_img_count = sub_img_count + ges_img_count
    #print("sub_img_count",sub_img_count)
final_img_count_test = final_img_count_test + sub_img_count        
print(final_img_count_test)
X_test = np.array(X_test, dtype = 'float32')
y_test = np.array(y_test)
#y_test = y_test.reshape(final_img_count_test, 1) # Reshape to be the correct size
#y_test = y_test.reshape(1, -1)
X_test.shape
 

6981


(179, 39, 120, 320)

In [11]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
y_test1 = encoder.fit_transform(y_test)
print(y_test1)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [21]:
final_seq_count_train=np.int(final_img_count_train/Seqlength)
final_seq_count_test=np.int(final_img_count_test/Seqlength)
X_train = X_train.reshape(final_seq_count_train,Seqlength, 120, 320, 1)
X_train /= 255
X_test = X_test.reshape((final_seq_count_test,Seqlength,120,320,1))
X_test /= 255
X_test.shape

(179, 39, 120, 320, 1)

In [30]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import LSTM

from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D,TimeDistributed
from keras.layers import Dropout

model = Sequential()
#TimeDistributed CNN 
model.add(TimeDistributed( Conv2D(32, (4, 4), activation='relu'), input_shape=(Seqlength, 120, 320, 1)))
model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))
model.add(TimeDistributed(Conv2D(32, (5,5), activation='relu')))
#extract features and dropout 
model.add(TimeDistributed(Flatten()))
#model.add(Dropout(0.5))
# input to LSTM
model.add(LSTM(32)) 

# classifier with sigmoid activation for multilabel

model.add(Dense(11, activation='sigmoid'))


model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed_17 (TimeDis (None, 39, 117, 317, 32)  544       
_________________________________________________________________
time_distributed_18 (TimeDis (None, 39, 58, 158, 32)   0         
_________________________________________________________________
time_distributed_19 (TimeDis (None, 39, 54, 154, 32)   25632     
_________________________________________________________________
time_distributed_20 (TimeDis (None, 39, 266112)        0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 32)                34066560  
_________________________________________________________________
dense_5 (Dense)              (None, 11)                363       
Total params: 34,093,099
Trainable params: 34,093,099
Non-trainable params: 0
________________________________________________________________

In [31]:
model.compile(optimizer=tf.train.AdamOptimizer(),
              loss='binary_crossentropy',
              metrics=['accuracy'])
 

In [32]:
 
epochs = 1
batch_size = 1
model.fit(X_train, y_train1, epochs=epochs, batch_size=batch_size)

Epoch 1/1
717/717 [==============================] - 6766s 9s/step - loss: 0.3136 - acc: 0.9076


In [ ]:
[loss, acc] = model.evaluate(X_test,y_test1,verbose=1)
print("Accuracy:" + str(acc) + ":" + "Loss:" + str(loss))